name: sdss_groups_ml

channels:
  - defaults
  - anaconda
  - conda-forge

dependencies:
  - python>=3.6
  - ipython
  - anaconda
  - astropy
  - h5py
  - graphviz
  - python-graphviz
  - numpy
  - pandas>=0.19.0
  - pydotplus
  - scipy
  - seaborn>=0.8.1
  - scikit-learn>=0.19.1
  - sphinx
  - xgboost
  - py-xgboost
  - pip
  - pip:
    - GitPython
    - progressbar2
    - sphinx_rtd_theme
    - tqdm
    - tables
    - xgboost
